{% set name = "thermoextrap" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/thermoextrap-{{ version }}.tar.gz
  sha256: 884fba5d383ca55be53f4eff0c791b59c022e5f1171c65327c4ebe32dc60efa3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.8,<3.12
    - attrs
    - cmomy >=0.8
    - lazy_loader
    - module-utilities >=0.2
    - numpy >=1.20
    - scipy
    - sympy
    - xarray >=0.16

test:
  imports:
    - thermoextrap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/thermoextrap
  summary: Thermodynamic extrapolation
  description: |
    A package to perform thermodynamic extrapolation of molecular simulations.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
