{% set name = "thermoextrap" %}
{% set version = "1.0.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/thermoextrap-{{ version }}.tar.gz
  sha256: 0dd8fef6bd3681d9c1b7bce6d0822cd971d48aa1f0ef291569954f88946e7b31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=24.1.0
    - cmomy >=1.0.1
    - dm-tree
    - lazy-loader
    - module-utilities >=0.11.0
    - numba >=0.60.0
    - numpy >=1.26.0
    - packaging
    - scipy
    - sympy
    - xarray >=2024.7.0

test:
  imports:
    - thermoextrap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/usnistgov/thermoextrap
  summary: Thermodynamic extrapolation
  description: |
    A package to perform thermodynamic extrapolation of molecular simulations.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
